### ISSUE TITLE
error on basic usage

### ISSUE THREAD

**Issue by sahil-lakhwani** [awslabs/eks-node-viewer#8]
I installed using `go install github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer@latest`

```
$ eks-node-viewer                       
2022/12/09 11:43:21 creating client, exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"
```

Credentials are correctly configured

**Comment by tzneal** [comment]
In your kubeconfig, what version is set for apiVersion?
```yaml
- name: arn:aws:eks:us-west-2:12345678:cluster/your-cluster-name
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
```
